import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pixelvega</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.image}>
          <Image
            className={styles.img}
            src="/programmer.svg"
            alt="Pixelvega working and having a tea"
            width={260}
            height={260}
          />
        </div>
        <h1 className={styles.title}>
          Welcome to <br></br>
          <span className={styles.highlight}>Pixelvega</span>'s home!
        </h1>
        <p className={styles.subtitle}>
          Sorry, there's nothing to see here. <br></br>Come back soon and maybe
          you'll be lucky {":)"}
        </p>
      </main>
    </div>
  );
}
