import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.scss"
import Snow from "../src/components/snow/snow"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pixelvega</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.image}>
          <Image
            className={styles.img}
            src="/programmer.svg"
            alt="Pixelvega working and having a tea"
            width={260}
            height={260}
          />
        </div>
        <Snow />
        <h1 className={styles.title}>
          Welcome to <br></br>
          <span className={styles.highlight}>Pixelvega</span>'s home!
        </h1>
        <p className={styles.subtitle}>
          Come back soon, a blizzard of exciting content is on the way!{" "}
        </p>
      </main>
    </div>
  )
}
